[ci] documented issue-closed workflow failure without a Linear issue (#43065)
# Why

This PR prevents failures in `.github/workflows/issue-closed.yml` when a
corresponding Linear issue cannot be found.

This happens rarely as a consequence of failed `🔎 Import issue to
Linear` in `.github/workflows/issue-triage.yml` but it happened in
https://github.com/expo/expo/actions/runs/21864091751/job/63100557088

```
Error: S.match is not a function - s.match is not a function
There was an error running import-github-issue-to-linear command: S.match is not a function - s.match is not a function
```

it's not immediately clear how that error should be resolved, and
re-running the action passed okay.

# How

- Added a comment to the "Close Linear issue" step in the GitHub
workflow
- Updated the `importIssueAsync` function to return the result of
`Linear.createIssueAsync` so that the result is awaited. That shouldn't
make any difference for this problem though

# Test Plan

- green CI

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources
according to [this short
guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style
Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)